### ISSUE TITLE
一点点建议

### ISSUE THREAD

**Issue by Dboy233** [liyuan1125/gorm-cache#1]
兄弟，我没有用你的库，但是我仔细看了一下源码，有很多参考学习意义。

1. 我看源码中只代理了Query，Update和Delete都没有做处理。
2. 缓存使用超时处理的，但是数据更新了，缓存没过期的时候得到的还是旧的数据。

我看go-zero的缓存处理，query raw的时候创建缓存，在update的时候更新缓存，remove的时候就清除缓存，query raws的时候不进行缓存。

库中有很多可以优化的地方。

**Comment by liyuan1125** [comment]
嗯，当初做这个库也是心血来潮，很多地方没有考虑到

按照目前的方式，缓存更新还无法做到，因为缓存key是sql语句

能想到的方式就是操作数据时删除所有缓存

或者自定义key可以做到；

例如查询所有指定用户
```sql
SELECT * FROM users where name = 'gorm';
```

将以上sql语句编码后作为key
删除时就比较麻烦了

可以想办法将key的规则定义一下
例如 `tableName`+`where`
删除的时候也是 `tableName`+`where`

这样的话或许可以
有时间可以优化下，您如果有好的想法欢迎PR

**Comment by Dboy233** [comment]
我也是在，gorm的提议中看到你的评论所以看了看，不过也有比较完善的缓存库，反正都是基于gorm的plugin 做的原理都一样。说实话，我是开发移动端的，golang 也是自己业余一直在学习，还处于新手
